version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "./__tests__/data"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "weekly"

